---
deployment:
  tasks:
    - export CI=true
    - npm install
    - npm run build
    - cp -R dist/ /home/dafq3exz/public_html/ # IMPORTANT: Replace 'yourusername' with your actual cPanel username
---